management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true

reader:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

server:
  port: 8080

#info:
#  app:
#    name: @project.artifactId@
#    description: @project.description@
#    version: @project.version@
